### ISSUE TITLE
Test 219 failing on luajit trunk

### ISSUE THREAD

**Issue by alexanius** [LuaJIT/LuaJIT-test-cleanup#19]
Hello.

$ luajit test.lua 219
[219/492] lib/string/format/num.lua --- ExploringBinary.com/print-precision-of-dyadic-fractions-varies-by-language/
lib/string/format/num.lua:13: expected string.format("%.99e", "0") == "4.940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359924e-324", but got "0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e+00"
stack traceback:
        [C]: in function 'error'
        lib/string/format/num.lua:13: in function 'check'
        lib/string/format/num.lua:163: in function <lib/string/format/num.lua:160>
        [C]: in function 'xpcall'
        test.lua:378: in function 'execute_plan'
        test.lua:413: in main chunk
        [C]: at 0x55fc2171a080
0 passed, 1 failed

x86_64 system, luajit revision: e296f56b825c688c3530a981dc6b495d972f3d01

**Comment by MikePall** [comment]
Fixed in LuaJIT/LuaJIT#817
