### ISSUE TITLE
Test 220 failing on luajit v2.1

### ISSUE THREAD

**Issue by jturnsek** [LuaJIT/LuaJIT-test-cleanup#20]
ubuntu@arm:~$ ./sandbox/orig/LuaJIT/src/luajit LuaJIT-test-cleanup/test/test.lua 220
[220/508] lib/string/format/num.lua --- ExploringBinary.com/print-precision-of-dyadic-fractions-varies-by-language/
LuaJIT-test-cleanup/test/lib/string/format/num.lua:13: expected string.format("%.99e", "0") == "4.940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359924e-324", but got "0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e+00"
stack traceback:
	[C]: in function 'error'
	LuaJIT-test-cleanup/test/lib/string/format/num.lua:13: in function 'check'
	LuaJIT-test-cleanup/test/lib/string/format/num.lua:163: in function <LuaJIT-test-cleanup/test/lib/string/format/num.lua:160>
	[C]: in function 'xpcall'
	LuaJIT-test-cleanup/test/test.lua:378: in function 'execute_plan'
	LuaJIT-test-cleanup/test/test.lua:413: in main chunk
	[C]: at 0x00469c01
0 passed, 1 failed

ARM system, luajit revision: 1d7b5029c5ba36870d25c67524034d452b761d27

**Comment by jturnsek** [comment]
It seems 9512d5c1aced61e13e7be2d3208ec7ae3516b458 is a culprit.

**Comment by MikePall** [comment]
Fixed in LuaJIT/LuaJIT#817
